package org.sample;

import java.io.File;
import java.io.StringWriter;
import java.io.Writer;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.w3c.dom.Comment;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class JUnitReport {

	
	public static void createXML() throws Exception
	{
		DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
		DocumentBuilder builder = factory.newDocumentBuilder();		
		Document doc = builder.newDocument();
		Element tsSuite = doc.createElement("testsuite");
		tsSuite.setAttribute("hostname","USHYDMMEDAVARA3");
		tsSuite.setAttribute("ignored","0");
		tsSuite.setAttribute("name","Test");
		tsSuite.setAttribute("tests","0");
		tsSuite.setAttribute("failures","0");
		tsSuite.setAttribute("timestamp","28 Mar 2018 06:16:20 GMT ");
		tsSuite.setAttribute("time","45.958");		
		tsSuite.setAttribute("errors","0");
		doc.appendChild(tsSuite);
		Comment preProcCom = doc.createComment("  Generated by org.testng.reporters.JUnitXMLReporter  ");
		tsSuite.getParentNode().insertBefore(preProcCom,tsSuite);		
		Transformer tf = TransformerFactory.newInstance().newTransformer();
		tf.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
		Writer out = new StringWriter();
		tf.transform(new DOMSource(doc), new StreamResult(System.getProperty("user.dir")+File.separator+"test-output\\Suite\\test2.xml"));
	}
	
	public void LogResults() throws Exception
	{

		
	}
}
